extends: stylelint-config-standard
syntax: scss
processors:
- - '@mapbox/stylelint-processor-arbitrary-tags'
  - fileFilterRegex: [/\.html$/]
plugins:
- stylelint-scss
rules:
# 关闭颜色16进制大小写
  color-hex-case: ~
#  no-empty-source: ~
  no-eol-whitespace: ~
  block-no-empty: ~
  color-no-invalid-hex: true
  comment-empty-line-before:
  - always
  - ignore:
    - stylelint-commands
    - after-comment
  indentation:
  - 2
  - except:
    - value
  max-empty-lines: 2
  unit-whitelist: [ px, '%', s, em, vw, vh, deg ]
  rule-empty-line-before:
  - always
  - except:
    - first-nested
    ignore:
    - after-comment
  at-rule-empty-line-before:
  - always
  - except:
    - first-nested
    ignore:
    - after-comment
    - blockless-after-same-name-blockless
    ignoreAtRules:
    - extend
    - include
    - if
    - else
  declaration-empty-line-before:
  - never

  # lost-column
  property-no-unknown:
  - true
  - ignoreProperties:
    - /^lost\-/

  # config for scss:
  at-rule-no-unknown:
  - true
  - ignoreAtRules:
    - extend
    - mixin
    - include
    - each
    - for
    - while
    - warn
    - at-root
  block-opening-brace-space-before:
  - always
  block-closing-brace-newline-after:
  - always
  - ignoreAtRules: [ if, else ]
  at-rule-name-space-after: always
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate

